-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	images = {
		game = {
			white_square = "rbxassetid://17010940576",
		},
		ui = {
			ball = "rbxassetid://17011300468",
			blur = "rbxassetid://17011099975",
		},
	},
}