-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	images = {
		game = {
			white_square = "rbxassetid://17010940576",
		},
		ui = {
			ball = "rbxassetid://17011300468",
			blur = "rbxassetid://17011099975",
			bucket = "rbxassetid://18559383985",
			city = "rbxassetid://18559424305",
			pool = "rbxassetid://18559414411",
			world = "rbxassetid://18559414557",
		},
	},
}